# 共通のeslintrc

root: true

extends:
  - airbnb
  - plugin:promise/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/react
  - prettier/@typescript-eslint

plugins:
  - promise
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: module
  project: ./tsconfig.json
  ecmaFeatures:
    jsx: false

settings:
  import/resolver:
    node:
      extensions:
        - .ts
        - .tsx
        - .js
        - .jsx

env:
  browser: true

rules:
  ###
  ### 以下は自分ルール
  ###

  # no-unused-vars を TypeScript用に
  no-unused-vars:
    - off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_ # _foo は許容

  # メソッドのthisはなくてもよい
  class-methods-use-this:
    - off

  # アロー関数のカッコは必ず必要
  arrow-parens:
    - error
    - always

  # consoleは限定
  no-console:
    - error
    - allow: [debug, warn, error]

  # export default は使わない
  import/prefer-default-export:
    - off
  import/no-default-export:
    - error

  # case の break 省略にはコメントが必要
  no-fallthrough:
    - error
    - commentPattern: thru

  # 関数戻り値の型はなくてもよい（ReturnTypeを使うため）
  '@typescript-eslint/explicit-function-return-type':
    - off

  # 継承なしの空インターフェースはエラーとする
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true

  # tsx を許容
  react/jsx-filename-extension:
    - error
    - extensions: ['.jsx', '.tsx']

  # importの順
  import/order:
    - error
    - newlines-between: always

  # 良さげな場所に空行を入れる
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: '*'
      next: return
    - blankLine: always
      prev: '*'
      next: expression
    - blankLine: any
      prev: expression
      next: expression
    - blankLine: always
      prev: '*'
      next: function
    - blankLine: never
      prev: '*'
      next: case
    - blankLine: always
      prev: '*'
      next: default
    - blankLine: always
      prev: '*'
      next: class
    - blankLine: always
      prev: '*'
      next: export
    - blankLine: always
      prev: '*'
      next: block-like
    - blankLine: always
      prev: '*'
      next: const
    - blankLine: always
      prev: const
      next: '*'
    - blankLine: any
      prev: const
      next: const
  ###
  ### 以下はプロジェクト固有のルール
  ###
