export const oldColors = {
  bg: {
    normal: 'bg-white',
    hover: '',
    disabled: 'bg-gray-200',
    invert: 'bg-gray-900',
    invertHover: 'bg-gray-800',
    invertDisabled: 'bg-gray-400',
    focus: 'bg-yellow-200',
    mark: 'bg-gray-700',
    markDisabled: 'bg-gray-200',
  },
  border: {
    normal: 'border-gray-700',
    hover: 'border-gray-900',
    disabled: 'border-gray-400',
    invert: 'border-gray-900',
    invertHover: 'border-gray-800',
    invertDisabled: 'border-gray-300',
    focus: 'border-blue-500',
  },
  text: {
    normal: 'text-gray-700',
    hover: 'text-gray-900',
    disabled: 'text-gray-400',
    invert: 'text-white',
    focus: 'text-black',
    invertHover: '',
    invertDisabled: 'text-gray-200',
  },
};

// prettier-ignore
export const colors = {
  standard:  {  normal:   { bg: 'bg-white',       border: 'border-gray-700',   text: 'text-gray-700' },
                hover:    { bg: '',               border: 'border-gray-900',   text: 'text-gray-900' },
                focus:    { bg: '',               border: 'border-blue-500',   text: 'text-gray-900 ' },
                disabled: { bg: 'bg-gray-200',    border: 'border-gray-400 ',  text: 'text-gray-400' }, },
  inverted: {   normal:   { bg: 'bg-gray-900',    border: 'border-gray-900',   text: 'text-white' },
                hover:    { bg: 'bg-gray-800',    border: 'border-gray-800',   text: '' },
                focus:    { bg: 'bg-gray-800 ',   border: 'border-gray-800 ',  text: '' },
                disabled: { bg: 'bg-gray-400',    border: 'border-gray-400',   text: 'text-gray-200' }, },
  mark:      {  normal:   { bg: 'bg-gray-700',    border: '',                  text: ''},
                hover:    { bg: 'bg-gray-400',    border: '',                  text: ''},
                focus:    { bg: 'bg-gray-400 ',   border: '',                  text: ''},
                disabled: { bg: 'bg-gray-400  ',  border: '',                  text: ''}, },
  focusRing: {  focus:    { bg: '',               border: 'border-blue-500',   text: '' }, },
  inputArea: {  normal:   { bg: 'white',          border: '',                  text: 'black' },
                focus:    { bg: 'bg-yellow-200',  border: '',                  text: 'black ' }, },
};
