module.exports = {
  theme: {
    extend: {
      colors: {
        gray: {
          100: '#fcfcfc',
          200: '#f3f3f3',
          300: '#e3e3e3',
          400: '#cecece',
          500: '#b4b4b4',
          600: '#969696',
          700: '#747474',
          800: '#4f4f4f',
          900: '#282828',
        },
      },
      fontSize: {
        xxs: '0.5rem',
      },
      minHeight: (theme) => ({
        ...theme('spacing'),
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
      }),
      maxHeight: (theme) => ({
        ...theme('spacing'),
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
      }),
      minWidth: (theme) => ({
        ...theme('spacing'),
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
      }),
      maxWidth: (theme) => ({
        ...theme('spacing'),
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
      }),
      zIndex: {
        99999: 99999,
      },
      inset: {
        full: '100%',
      },
    },
  },
  variants: {
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    appearance: [],
    backgroundAttachment: false,
    backgroundColor: ['hover', 'focus', 'active', 'invalid'],
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    borderCollapse: false,
    borderColor: [
      'hover',
      'focus',
      'active',
      'invalid',
      'focus-within',
      'focus-parent',
    ],
    borderRadius: [],
    borderStyle: [],
    borderWidth: ['focus', 'active', 'invalid', 'focus-within'],
    boxShadow: ['hover', 'focus', 'active'],
    cursor: ['hover'],
    display: [],
    fill: false,
    flex: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: false,
    fontFamily: false,
    fontSize: [],
    fontSmoothing: false,
    fontStyle: [],
    fontWeight: ['hover', 'focus'],
    height: [],
    inset: [],
    justifyContent: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: false,
    listStyleType: false,
    margin: ['focus-after'],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    objectFit: false,
    objectPosition: [],
    opacity: ['hover', 'active', 'invalid'],
    order: [],
    outline: ['focus', 'active'],
    overflow: [],
    padding: ['focus', 'active', 'invalid', 'focus-within'],
    pointerEvents: [],
    position: [],
    resize: [],
    stroke: false,
    tableLayout: false,
    textAlign: [],
    textColor: ['hover', 'focus', 'active', 'invalid', 'focus-parent'],
    textDecoration: ['hover', 'focus'],
    textTransform: false,
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: [],
    wordBreak: [],
    zIndex: ['focus', 'focus-within'],
  },
  plugins: [
    require('./invalid')(),
    require('./focus-parent')(),
    require('./focus-after')(),
  ],
};
